// input macro:
//   ELEM_SIZE_FILE_NAME

#define VALUE_SIZE 1
#define FAST_ELEM_SIZE 1
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE

#define VALUE_SIZE 2
#define FAST_ELEM_SIZE 2
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE

#define VALUE_SIZE 4
#define FAST_ELEM_SIZE 4
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE

#if TERARK_C_MAX_VALUE_SIZE >= 8 && 8 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 8
#define FAST_ELEM_SIZE 8
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 12 && 12 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 12
#define FAST_ELEM_SIZE 12
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 16 && 16 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 16
#define FAST_ELEM_SIZE 16
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 20 && 20 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 20
#define FAST_ELEM_SIZE 20
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 24 && 24 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 24
#define FAST_ELEM_SIZE 24
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 28 && 28 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 28
#define FAST_ELEM_SIZE 28
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 32 && 32 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 32
#define FAST_ELEM_SIZE 32
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 36 && 36 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 36
#define FAST_ELEM_SIZE 36
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 40 && 40 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 40
#define FAST_ELEM_SIZE 40
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 44 && 44 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 44
#define FAST_ELEM_SIZE 44
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 48 && 48 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 48
#define FAST_ELEM_SIZE 48
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 52 && 52 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 52
#define FAST_ELEM_SIZE 52
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 56 && 56 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 56
#define FAST_ELEM_SIZE 56
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 60 && 60 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 60
#define FAST_ELEM_SIZE 60
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 64 && 64 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 64
#define FAST_ELEM_SIZE 64
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 68 && 68 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 68
#define FAST_ELEM_SIZE 68
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 72 && 72 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 72
#define FAST_ELEM_SIZE 72
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 76 && 76 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 76
#define FAST_ELEM_SIZE 76
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 80 && 80 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 80
#define FAST_ELEM_SIZE 80
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 84 && 84 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 84
#define FAST_ELEM_SIZE 84
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 88 && 88 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 88
#define FAST_ELEM_SIZE 88
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 92 && 92 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 92
#define FAST_ELEM_SIZE 92
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 96 && 96 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 96
#define FAST_ELEM_SIZE 96
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 100 && 100 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 100
#define FAST_ELEM_SIZE 100
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 104 && 104 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 104
#define FAST_ELEM_SIZE 104
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 108 && 108 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 108
#define FAST_ELEM_SIZE 108
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 112 && 112 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 112
#define FAST_ELEM_SIZE 112
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 116 && 116 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 116
#define FAST_ELEM_SIZE 116
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 120 && 120 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 120
#define FAST_ELEM_SIZE 120
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 124 && 124 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 124
#define FAST_ELEM_SIZE 124
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 128 && 128 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 128
#define FAST_ELEM_SIZE 128
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 132 && 132 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 132
#define FAST_ELEM_SIZE 132
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 136 && 136 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 136
#define FAST_ELEM_SIZE 136
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 140 && 140 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 140
#define FAST_ELEM_SIZE 140
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 144 && 144 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 144
#define FAST_ELEM_SIZE 144
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 148 && 148 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 148
#define FAST_ELEM_SIZE 148
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 152 && 152 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 152
#define FAST_ELEM_SIZE 152
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 156 && 156 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 156
#define FAST_ELEM_SIZE 156
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 160 && 160 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 160
#define FAST_ELEM_SIZE 160
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 164 && 164 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 164
#define FAST_ELEM_SIZE 164
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 168 && 168 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 168
#define FAST_ELEM_SIZE 168
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 172 && 172 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 172
#define FAST_ELEM_SIZE 172
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 176 && 176 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 176
#define FAST_ELEM_SIZE 176
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 180 && 180 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 180
#define FAST_ELEM_SIZE 180
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 184 && 184 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 184
#define FAST_ELEM_SIZE 184
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 188 && 188 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 188
#define FAST_ELEM_SIZE 188
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 192 && 192 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 192
#define FAST_ELEM_SIZE 192
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 196 && 196 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 196
#define FAST_ELEM_SIZE 196
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 200 && 200 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 200
#define FAST_ELEM_SIZE 200
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 204 && 204 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 204
#define FAST_ELEM_SIZE 204
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 208 && 208 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 208
#define FAST_ELEM_SIZE 208
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 212 && 212 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 212
#define FAST_ELEM_SIZE 212
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 216 && 216 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 216
#define FAST_ELEM_SIZE 216
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 220 && 220 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 220
#define FAST_ELEM_SIZE 220
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 224 && 224 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 224
#define FAST_ELEM_SIZE 224
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 228 && 228 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 228
#define FAST_ELEM_SIZE 228
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 232 && 232 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 232
#define FAST_ELEM_SIZE 232
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 236 && 236 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 236
#define FAST_ELEM_SIZE 236
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 240 && 240 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 240
#define FAST_ELEM_SIZE 240
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 244 && 244 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 244
#define FAST_ELEM_SIZE 244
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 248 && 248 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 248
#define FAST_ELEM_SIZE 248
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 252 && 252 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 252
#define FAST_ELEM_SIZE 252
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

#if TERARK_C_MAX_VALUE_SIZE >= 256 && 256 % TERARK_C_STRUCT_ALIGN == 0
#define VALUE_SIZE 256
#define FAST_ELEM_SIZE 256
#include ELEM_SIZE_FILE_NAME
#undef VALUE_SIZE
#undef FAST_ELEM_SIZE
#endif

